"""create game

Revision ID: d94933b941e8
Revises: 91fc40d84811
Create Date: 2025-08-28 09:59:54.797202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd94933b941e8'
down_revision: Union[str, Sequence[str], None] = '91fc40d84811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('board_size', sa.Integer(), nullable=False),
    sa.Column('mines', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_results_id'), 'game_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_results_id'), table_name='game_results')
    op.drop_table('game_results')
    # ### end Alembic commands ###
